//

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";

import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { PopupWidget }  from "@/components/PopupWidget";
import LayoutWrapper from "@/components/LayoutWrapper";


const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create iMakeSite App",
  description: "Generated by iMakeSite",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LayoutWrapper>{children}</LayoutWrapper>
  );
}
