// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import { getHeaderData, getFooterData } from "@/lib/fetch";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { PopupWidget }  from "@/components/PopupWidget";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const headerData = await getHeaderData();
  const footerData = await getFooterData();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class">
          <Navbar headerData={headerData}/>
          <div>{children}</div>
          <Footer  footerData={footerData}/>
          <PopupWidget />
        </ThemeProvider>
      </body>
    </html>
  );
}







// import 'bootstrap/dist/css/bootstrap.min.css';
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import { ThemeProvider } from "next-themes";
// // import "./globals.css";
// // import '../styles/globals.css';
// const inters = Inter({ subsets: ["latin"] });

// import { Navbar } from "@/components/Navbar";
// import { Footer } from "@/components/Footer";
// import { PopupWidget }  from "@/components/PopupWidget";
// import LayoutWrapper from "@/components/LayoutWrapper";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create iMakeSite app for PEPSI Replica",
//   description: "Generated by iMakeSite",
//   icons: {
//     icon: "/favicon.ico"
//   }
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <head>
//         {/* GrapesJS CSS */}
//         <link
//           rel="stylesheet"
//           href="https://unpkg.com/grapesjs/dist/css/grapes.min.css"
//           crossOrigin="anonymous"
//         />

//   {/* Bootstrap CSS (optional, only keep if you need it) */}
//   {/* <link
//     rel="stylesheet"
//     href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
//     crossOrigin="anonymous"
//   /> */}

//   {/* Font Awesome */}
//   <link
//     rel="stylesheet"
//     href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
//     crossOrigin="anonymous"
//   />
//       </head>
//       <body className={inters.className}>
//         <LayoutWrapper>{children}</LayoutWrapper>
//       </body>
//     </html>
//   );
// }








// // components/LayoutWrapper.tsx
// import { Navbar } from "@/components/Navbar";
// import { Footer } from "@/components/Footer";
// import { PopupWidget } from "@/components/PopupWidget";
// import { ThemeProvider } from "next-themes";
// import { Inter } from "next/font/google";
// import 'bootstrap/dist/css/bootstrap.min.css';
// import { getHeaderData, getFooterData } from "@/lib/fetch"; // your data fetch function
// import './../../styles/globals.css'
// const inter = Inter({ subsets: ["latin"] });

// export default async function LayoutWrapper({ children }: { children: React.ReactNode }) {
//   const headerData = await getHeaderData();
//   const footerData = await getFooterData();


//   return (
//     <div>
//       <ThemeProvider attribute="class">
//         <Navbar headerData={headerData} />
//         <div>{children}</div>
//         <Footer footerData={footerData}/>
//         <PopupWidget />
//       </ThemeProvider>
//     </div>
//   );
// }
